# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qcbinomC <- function(p, m, g, lowertail = TRUE, logp = FALSE, rcb = FALSE) {
    .Call(`_cbinom_qcbinomC`, p, m, g, lowertail, logp, rcb)
}

dcblp <- function(x, m, g) {
    .Call(`_cbinom_dcblp`, x, m, g)
}

